sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
      - sourceline: "deb http://01.archive.ubuntu.com/ubuntu/ precise main"
    packages:
      - g++-5
      - python3.5
      - libsqlite3-dev
      - libboost-all-dev
      - libssl-dev

language: python
python:
  - "3.5"
install:
  - pip3 install --upgrade flake8
  - sudo unlink /usr/bin/g++
  - sudo ln /usr/bin/g++-5 /usr/bin/g++
script:
  - "python3 -m flake8 src"
  - "cd src && ./build.sh -t daemon && cd ../"
