sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
      - deadsnakes
    packages:
      - g++-5
      - python3.5
      - libsqlite3-dev
      - libboost-all-dev
      - libssl-dev

language: python
python:
  - "3.5"
install:
  - pip3 install --upgrade flake8
script:
  - "python3 -m flake8 src"
